### ISSUE TITLE
AppleALC - Problem with two physical soundcards

### ISSUE THREAD

**Issue by ninjuan11** [acidanthera/bugtracker#1000]
Hello,
this seems like a rare bug, it only occurs when a system has two sound cards, where one is not supported by applealc.
In this case, after inserting the card, the onboard stops working. The device is visible to osx and both cards work fine in windows or linux.

Even when using fake vendor-id or class-code the not supported card will be initialized and will be set as HDEF
Removing any layout-id from the config didnt work. The layout-id on the other card gets ignored, even if it is the only layout-id in the configuration.

In this setup it's a ALC1220 vs a Sound-Blaster. The ALC1220 does show up as AZAL in ioregistry.

[EFI.zip](https://github.com/acidanthera/bugtracker/files/4833779/EFI.zip)
[opencore-2020-06-25-204612.txt](https://github.com/acidanthera/bugtracker/files/4833781/opencore-2020-06-25-204612.txt)
[ioRegistry.zip](https://github.com/acidanthera/bugtracker/files/4833784/ioRegistry.zip)
[DSDT.aml.zip](https://github.com/acidanthera/bugtracker/files/4833785/DSDT.aml.zip)

**Comment by vit9696** [comment]
Please provide a Lilu log. Add to boot arguments: `liludump=60 -liludbgall`, use DEBUG AppleALC and Lilu, attach the file at `/var/log/Lilu_x.x.x.txt` directory 60 seconds after booting.

Also, I believe this should be resolved just fine upon injecting `class-code = <FF FF FF FF>` to your Sound-Blaster audio card via DeviceProperties. To get the device path you can always use gfxutil.

**Comment by ninjuan11** [comment]
I already added class-code in the file, didn’t fix it.
I‘ll create the log afap

**Comment by vit9696** [comment]
Well, I cannot even open your config.plist `The document “config.plist” could not be opened. The data is not in the correct format.`, and I would strongly recommend DeviceProperties to ACPI.

**Comment by ninjuan11** [comment]
yes, i removed a part of the config.plist - the part with the serial numbers. thats why you cant open it.

**Comment by vit9696** [comment]
I do not believe removing any part of the configuration will make it unparsable. You did something mad there.

I mean that you should add `class-code` via DeviceProperties instead of ACPI tables. Just run `gfxutil -f HDEF` (can be downloaded from Acidanthera), then create a section with that device path and add `class-code = <FF FF FF FF>`.

**Comment by ninjuan11** [comment]
i removed it and wrote REMOVED in big letters in there.
i have class-code set to FF FF FF FF in deviceproperties on the device
```
			<key>PciRoot(0x0)/Pci(0x1,0x2)/Pci(0x0,0x0)/Pci(0x3,0x0)/Pci(0x0,0x0)/Pci(0x0,0x0)</key>
			<dict>
				<key>AAPL,slot-name</key>
				<string>Internal@0,1,2/0,0@5,0,0</string>
				<key>class-code</key>
				<data>
				/////w==
				</data>
```

**Comment by vit9696** [comment]
Are you positive this is a correct device path? Because I do not see this class-code in your device. There is an SSDT with DSM, and ACPI has precedence, so maybe something is confused here?

**Comment by ninjuan11** [comment]
well it's the device displayed in hackintool and gfxutil.
```
gfxutil-1.80b-RELEASE % ./gfxutil -f HDEF
05:00.0 1102:0010 /PCI0@0/BXBR@1,2/BYUP@0/BYD3@3/BYS3@0/HDEF@0 = PciRoot(0x0)/Pci(0x1,0x2)/Pci(0x0,0x0)/Pci(0x3,0x0)/Pci(0x0,0x0)/Pci(0x0,0x0)
```

**Comment by vit9696** [comment]
I think the issue is with your ACPI tables to be honest. And am I going to get the log?

**Comment by ninjuan11** [comment]
I would love to, but seems like the rapid restarting broke my nvme SSD. I've ordered a new one in my local store and will pick it up in a few minutes and reinstall osx completely. then I will supply the logs.

But one finding before everything broke down: applealc is renaming the soundblaster to HDEF and the other parts from the device properties is successfully injected in the device. 

thank you very much for your help.

**Comment by ninjuan11** [comment]
[with-soundblaster-and-classcode.txt](https://github.com/acidanthera/bugtracker/files/4838860/with-soundblaster-and-classcode.txt)
[with-soundblaster.txt](https://github.com/acidanthera/bugtracker/files/4838862/with-soundblaster.txt)
[without-soundblaster.txt](https://github.com/acidanthera/bugtracker/files/4838863/without-soundblaster.txt)
here are the log files with each setup. one with physical removed soundblaster, one with soundblaster inserted and one with soundblaster inserted and class code injection

**Comment by vit9696** [comment]
Are there soundblaster drivers for macOS at all? I.e. what is the preferred approach — ignore this device or disable it? I can add some special property for this if necessary, but it depends on what is needed.

**Comment by ninjuan11** [comment]
well if the soundblaster would be compatible, it would be a charm, but i think this is way too much work. it would be fine if the soundblaster would be ignored and applealc would use the internal instead.

**Comment by benbender** [comment]
@ninjuan11 Try to shutdown the PCI-Port via ACPI when booting OSX. See https://github.com/daliansky/OC-little/tree/master/17-%E7%A6%81%E6%AD%A2PCI%E8%AE%BE%E5%A4%87

**Comment by vit9696** [comment]
That's a good idea, but just in case there are drivers for such a card some time I added a DeviceProperty `external-audio` to let the user explicitly mark the audio card as external.

**Comment by ninjuan11** [comment]
so I can simply set external-audio on the card in device properties and it's working?

**Comment by ninjuan11** [comment]
ok I can confirm - it's working! thank you very much!

**Comment by CiriousJoker** [comment]
omg finally, I've been trying to fix this issue for so long...

**Comment by ninjuan11** [comment]
@vit9696 is it possible that this feature is broken in 11.0.1? 
The ioregistryexplorer tells me, that the device has "external-audio" set to Data 01 00 00 00, but it got HDEF again. :(

**Comment by ninjuan11** [comment]
> @ninjuan11 Try to shutdown the PCI-Port via ACPI when booting OSX. See https://github.com/daliansky/OC-little/tree/master/

@vit9696 see attached image - be aware it is after using the untitled.dsl from below. otherwise the path is different.
![ioreg](https://user-images.githubusercontent.com/67441126/99919269-aa094300-2d1c-11eb-9893-567b82cd1fa8.png)
![ioreg2](https://user-images.githubusercontent.com/67441126/99919320-f2c0fc00-2d1c-11eb-8c07-7ab787fca253.png)

@benbender i tried to disable with supplied ssdt, but did not work. it got a new ioreg name instead. Maybe can you see what i'm doing wrong?
[Untitled.dsl.txt](https://github.com/acidanthera/bugtracker/files/5580531/Untitled.dsl.txt)
![hackintool](https://user-images.githubusercontent.com/67441126/99919308-de7cff00-2d1c-11eb-8187-f3c3f148b295.png)
