### ISSUE TITLE
Early kernel panic with latest OpenCorePkg commit

### ISSUE THREAD

**Issue by ZISQO** [acidanthera/bugtracker#1013]
today i was update newerly OC binary that after commit 44081eb0
but Catalina 10.15.5 and BS beta 1 both failed to boot at the "unable to find driver for this platform: \"ACPI\".n\" mesg.

![11](https://user-images.githubusercontent.com/50421769/85965638-417d9a80-b9f8-11ea-95cc-afb8340b9f9f.png)
- this is ASUS X299 TUF mk1

![image0](https://user-images.githubusercontent.com/50421769/85965891-29f2e180-b9f9-11ea-8816-d49ffe2a4b21.png)
- this is Gigabyte Z370 Gaming 5

![image0](https://user-images.githubusercontent.com/50421769/85969604-1ea4b380-ba03-11ea-9235-02f21f0d7321.jpg)
- this is Gigabyte Z370 Gaming 7

**Comment by dhinakg** [comment]
I can reproduce with Catalina on a i7-6700HQ laptop (Big Sur not tested). Commit 44081eb08b379e3be082df89e4490f3bb89ad23c.
![image](https://user-images.githubusercontent.com/17605561/85966562-2c6c2180-b98e-11ea-9e52-5da0520c4908.png)
[EFI.zip](https://github.com/acidanthera/bugtracker/files/4843425/EFI.zip)
[opencore-2020-06-29-020943.txt](https://github.com/acidanthera/bugtracker/files/4843426/opencore-2020-06-29-020943.txt)

**Comment by ZISQO** [comment]
ty @khronokernel

**Comment by vit9696** [comment]
Thanks for the report. Should be fixed in master. Let me know if the issue persists.

**Comment by ZISQO** [comment]
> Thanks for the report. Should be fixed in master. Let me know if the issue persists.

yes i will report it for us! ty @vit9696

**Comment by MachInit** [comment]
> Thanks for the report. Should be fixed in master. Let me know if the issue persists.

Issue has reappeared in commit 275c78b with the same error.

**Comment by vit9696** [comment]
Are you sure it is `275c78b`? I do not see any particularly bad. Also, it will help to see the log.

**Comment by Rescticed** [comment]
i booted fine no issues. 
[opencore-2020-06-29-214341.txt](https://github.com/acidanthera/bugtracker/files/4848339/opencore-2020-06-29-214341.txt)

**Comment by Andrey1970AppleLife** [comment]
I don't confirm a bug. Works fine.

**Comment by dhinakg** [comment]
Both acidanthera/OpenCorePkg@275c78b and latest master (acidanthera/OpenCorePkg@2ae43ab055cbe8d9b161215fc9c6c83e945fcb13) are working fine here.

**Comment by martinxxd** [comment]
I'm on [acidanthera/OpenCorePkg@2ae43ab](https://github.com/acidanthera/OpenCorePkg/commit/2ae43ab055cbe8d9b161215fc9c6c83e945fcb13) too, and works perfectly fine.

**Comment by MachInit** [comment]
Let me double check just to confirm that something didn't cross while compiling.

**Comment by MachInit** [comment]
*Resolved*

Issues with Git pulling the wrong commit and reporting that 44081eb0 was 275c78b. Purged and recompiled. All seems to work. Sorry for the issue.

**Comment by Pavo-IM** [comment]
Getting so close on booting with the latest commit to master, with the new kernelcollections method. Looks like kext injection is working now, but still getting a panic.
![IMG_0081](https://user-images.githubusercontent.com/33814640/86540109-62e6f680-bed0-11ea-9912-d5333f94d765.jpeg)
Any suggestions?

**Comment by marianopela** [comment]
> Any suggestions?

I saw your other post regarding AirportBrcmFixup. Does it mean this is solved? I’m too getting an early KP with latest commit
