### ISSUE TITLE
Unable to boot Hyper-V (Windows 11) + macOS Montery (v12.1.16)

### ISSUE THREAD

**Issue by sofakng** [acidanthera/bugtracker#2159]
I'm using OpenCore v0.8.6 on Windows 11 (22H2) but I'm unable to boot macOS Monterey installation.

Here is the debug log:  [opencore-2022-11-15-164445.txt](https://github.com/acidanthera/bugtracker/files/10016433/opencore-2022-11-15-164445.txt)

Here is my config.plist:  [config.zip](https://github.com/acidanthera/bugtracker/files/10016440/config.zip)

The host machine is an Intel i7-8700k so I first followed the instructions for Coffee Lake:  https://dortania.github.io/OpenCore-Install-Guide/config.plist/coffee-lake.html

...and then I followed the Hyper-V instructions:  https://github.com/acidanthera/MacHyperVSupport

The first errors (?) in the log shows this:
```
10:884 00:002 OCABC: No slide values are usable! Falling back to 4 with 0x03B00000 bytes!
10:886 00:002 AAPL: #[EB.H.IS|!] Err(0xE) <- RT.GV boot-signature 7C436110-AB2A-4BBB-A880-FE41995C9F82
10:889 00:002 AAPL: #[EB.H.IS|!] Err(0xE) <- RT.GV boot-image-key 7C436110-AB2A-4BBB-A880-FE41995C9F82
```

Can anybody help me out?

**Comment by pigworlds** [comment]
You don't need to apply any host config in your config.plist, like ACPI stuff, quirks. You should just have SSDT-HV-VMBUS, SSDT-HV-DEV, SSDT-DEV-WS2022, SSDT-HV-PLUG in the ACPI section.
Non hyper-v kexts like WEG is not necessary.
Hope this helps.

**Comment by pigworlds** [comment]
You can keep the serial number from Sample.plist. It is working fine. I recall the SystemUUID can't be all zero in some point, but it is fixed now.

I found there is one option `RebuildAppleMemoryMap` - required for macOS 10.6 and older. If you set it to true, the latest macOS 13 isn't happy, so I leave it as false. Everything else pretty much what the [document](https://github.com/acidanthera/MacHyperVSupport/blob/master/README.md) describes.

You can take a look on my [sample config](https://gist.github.com/pigworlds/870f6072889de4b8b25b05ab24c4236e).

**Comment by sofakng** [comment]
Thanks so much!  However, I think I'm getting further but still unable to boot:
![Screenshot 2022-12-15 133846](https://user-images.githubusercontent.com/2228499/207941022-8b87c018-eafb-413c-9f7c-eb882b58c4d7.png)

Here is the log (truncated to when it attempts to boot):
[partial-log.txt](https://github.com/acidanthera/bugtracker/files/10239752/partial-log.txt)

What version of macOS are you able to boot?  I'm using macOS Monterey (12) because I thought I'd have better luck than using Ventura (13).

The only other possibly difference is that I'm using a VHDX boot disk (FAT32) instead of a real USB drive.

Any other thoughts? :(

**Comment by pigworlds** [comment]
Your log shows it failed pretty early. Usually I see the last line EB EXITBS before jumping to the kernel logs, and you haven't reached that point.

I use fat32 VHDX boot disk too, and I have no problem booting macOS 10.12.6 to 13.1 under hyper-v, on an Intel 8th gen processor. I just installed macOS 12.6.2, 13.1 and they both ran properly. 

Have you tried my [config.plist](https://gist.github.com/pigworlds/870f6072889de4b8b25b05ab24c4236e) to see if it works for you?

**Comment by sofakng** [comment]
Yeah I'm using that file and it still doesn't boot.

I've tried the following recovery/boot images:

Monterey:
`python3 ./macrecovery.py -b Mac-E43C1C25D4880AD6 -m 00000000000000000 download`

and

Big Sur:
`python3 ./macrecovery.py -b Mac-42FD25EABCABB274 -m 00000000000000000 download`

Maybe I'm using the wrong combination/versions of the kExts or ACPI files?  Could you possible ZIP your boot disk (with or without the macOS recovery files) ?

I'm so sorry but I am so thankful for your help!

**Comment by pigworlds** [comment]
I have no idea about this error.

I previously saw boot failure after EXITBS due to unsupported CPU. I can work around by spoofing the CPUID, maybe you can try it to see if it improves?
> 			<key>Cpuid1Data</key>
>			<data>6gYJAAAAAAAAAAAAAAAAAA==</data>
>			<key>Cpuid1Mask</key>
>			<data>/////wAAAAAAAAAAAAAAAA==</data>

**Comment by sofakng** [comment]
Thanks again so much for all of the help.  Unfortunately it still doesn't boot even after the CPUID spoofing.  It's also strange because I am using an 8th generation CPU (i7-8700k) just like you.

Here is my latest log file:
[opencore-2022-12-19-095533.txt](https://github.com/acidanthera/bugtracker/files/10260242/opencore-2022-12-19-095533.txt)

For one final attempt, can you possibly share your entire EFI folder so I can try to boot with your exact files?

Thank you again so much for all of your help!

**Comment by vit9696** [comment]
I would say aside from #2135 we are unaware of Hyper-V issues. This better goes to the support forums.
