### ISSUE TITLE
igfxblr enable-backlight-registers-fix Break in 13.4 (Fixed by Apple in 13.5)

### ISSUE THREAD

**Issue by Edwardwich** [acidanthera/bugtracker#2241]
after update to 13.3 22E5236f WhateverGreen have problem now screen backlight not work need put device in sleep and wake up to solve this issue 

cpu: i5 8265u 
laptop :hp da1023nia
git link:
https://github.com/Edwardwich/hp-DA1023nia-macOS
opencore version : 9.1
https://github.com/acidanthera/OpenCorePkg/actions/runs/4378398015
EFI : 
[OC.zip](https://github.com/acidanthera/bugtracker/files/10949557/OC.zip)
log : 
[log.zip](https://github.com/acidanthera/bugtracker/files/10949562/log.zip)
IORegistry : 
[ali’s MacBook Pro.zip](https://github.com/acidanthera/bugtracker/files/10949566/ali.s.MacBook.Pro.zip)

**Comment by Edwardwich** [comment]
also try 1.6.3 same problem

**Comment by win1010525** [comment]
The same with i7-10510U

**Comment by abenraj** [comment]
Seems to have been a regression from Apple's end (to be _fairly_ expected on pre-release/Beta builds), which is (unsurprisingly) no longer present with the _Release Candidate_ version of macOS 13.3; both of WEG's reportedly broken backlight-patches (`-igfxblr` & `-igfxbls`) continue to be functional on macOS' Release channels.

**Comment by Edwardwich** [comment]
> Seems to have been a regression from Apple's end (to be _fairly_ expected on pre-release/Beta builds), which is (unsurprisingly) no longer present with the _Release Candidate_ version of macOS 13.3; both of WEG's reportedly broken backlight-patches (`-igfxblr` & `-igfxbls`) continue to be functional on macOS' Release channels.

I wait for fix this and update to 13.3RC

**Comment by abenraj** [comment]
> I wait for fix this and update to 13.3RC

Hi - there is nothing to fix here; backlight-patches working just fine on final release build of macOS 13.3 rendering this ticket invalid with respect to Acidanthera projects.

Best to close the issue, thanks!

**Comment by Edwardwich** [comment]
@abenraj this problem happen after update to 13.4 release

**Comment by abenraj** [comment]
Thanks for reporting - looks like Apple let this one slip to final release of 13.4, albeit doesn't seem to be the case on 13.5; patches are functional again as of 13.5 Beta 1 (22G5027e).

(I suppose this tracker can be left open till 13.5 release)

**Comment by Edwardwich** [comment]
> Thanks for reporting - looks like Apple let this one slip to final release of 13.4, albeit doesn't seem to be the case on 13.5; patches are functional again as of 13.5 Beta 1 (22G5027e).
> 
> (I suppose this tracker can be left open till 13.5 release)

Still use 13.3 and wait for 13.5?

**Comment by abenraj** [comment]
If these patches are a must for your use-case, then yes, that'd be the recommended course of action.

**Comment by mandresve** [comment]
> Thanks for reporting - looks like Apple let this one slip to final release of 13.4, albeit doesn't seem to be the case on 13.5; patches are functional again as of 13.5 Beta 1 (22G5027e).
> 
> (I suppose this tracker can be left open till 13.5 release)

Can confirm this.

**Comment by Edwardwich** [comment]
> > Thanks for reporting - looks like Apple let this one slip to final release of 13.4, albeit doesn't seem to be the case on 13.5; patches are functional again as of 13.5 Beta 1 (22G5027e).
> > (I suppose this tracker can be left open till 13.5 release)
> 
> Can confirm this.

try 13.5 b1 I think its ok

**Comment by mandresve** [comment]
> > > Thanks for reporting - looks like Apple let this one slip to final release of 13.4, albeit doesn't seem to be the case on 13.5; patches are functional again as of 13.5 Beta 1 (22G5027e).
> > > (I suppose this tracker can be left open till 13.5 release)
> > 
> > 
> > Can confirm this.
> 
> try 13.5 b1 I think its ok

Indeed, 13.5 beta isn't affected by the bug and current patches work well

**Comment by WuLongMiTaoLaiYiDa** [comment]
break in 13.4 ， Automatically light up after 5 minutes

**Comment by djtabu** [comment]
I hope it's a simple bug

**Comment by mandresve** [comment]
> I tried adding the -igfxblr, was already in the boot-arts.. I'm quite new to this, thou I'm trying to fix this really annoying problem. Should I add the dev-property too?

If the machine is booting successfully, you probable just need -igfxblr or -igfxbls in boot args. If experiencing issues in 13.4, enroll to the beta updates and update to 13.5 beta 1, or just wait for the upcoming official releases of Ventura & this patch.

**Comment by scorpion2002** [comment]
> > I tried adding the -igfxblr, was already in the boot-arts.. I'm quite new to this, thou I'm trying to fix this really annoying problem. Should I add the dev-property too?
> 
> If the machine is booting successfully, you probably just need -igfxblr or -igfxbls in boot args. If experiencing issues in 13.4, enroll to the beta updates and update to 13.5 beta 1, or just wait for the upcoming official releases of Ventura & this patch.

Thanks, I forgot to come back for an update. I enrolled for the beta and got 13.5 b2, problem is resolved. Its okay if I just leave the igfblr in boot=args yes. Either way updating definitely easier

**Comment by olekor** [comment]
Unfortunately in my case Surface Pro 5 Kaby Lake, Intel HD620 Ventura 13.6.1 this problem still presents and after plenty of attempts to fix it by using all the ways described method from different sources, I still can't find a solution to what way to find out.  It very curious about how it happened, I installed fresh Ventura 13.6.1 and used it within 3 days without any problem, but after connecting the external monitor and repeating the loading system the screen of the surface didn't switch on, only started working in the coupling, if disconnecting external while in working system the Surface screen as well getting black and don't back to light at all, as should be after 3-5 min. As other users have said.
