### ISSUE TITLE
Not loaded Recovery (10.13.6)

### ISSUE THREAD

**Issue by DHARVED** [acidanthera/bugtracker#389]
If choose a Recovery, OC Picker freezes and does not respond to action. It helps only reboot.

[opencore.log.zip](https://github.com/acidanthera/bugtracker/files/3283102/opencore.log.zip)
https://applelife.ru/threads/opencore-obsuzhdenie-i-ustanovka.2944066/page-37#post-810773

**Comment by vit9696** [comment]
This will want logging to be added through the dmg loading code in some future and trying to debug it. Recovery partition is valid, and the issue does not depend from the disk used. Watchdog is disabled.

**Comment by Download-Fritz** [comment]
I fixed a bug in the DMG loading code: https://github.com/acidanthera/OcSupportPkg/commit/9439d500942eb57975a5a0015a4afc1cb2a30e02
as well as made a defensive change for possible driver assumptions: https://github.com/acidanthera/OcSupportPkg/commit/8ab711512a03965f3cbe7374a191a8f4395ce7b6
and added further logging: https://github.com/acidanthera/OcSupportPkg/commit/6e71cca4073a1322d6fe8fa14af8f8c02b97a9ea

@DHARVED  I do not believe your issue is fixed, but please create a new log in case we'll get more debug output from the changes now.

**Comment by DHARVED** [comment]
@Download-Fritz yes, this did not solve the problem. I post a new log. Now OC does not freeze, but stops at "Halting on critical error"
[opencore.log.zip](https://github.com/acidanthera/bugtracker/files/3293854/opencore.log.zip)

**Comment by Download-Fritz** [comment]
@DHARVED I am sorry, your Recovery entry was not recognised as such because of a bug fixed at https://github.com/acidanthera/OcSupportPkg/commit/c3399b826bcc4c04cc57e7ac5fe33f74679fb8f3, hence it doesn't freeze anymore. Could you please re-do the log with the latest OcSupportPkg commit?

**Comment by DHARVED** [comment]
@Download-Fritz no problem. But it seems the log is not become more detailed. I use bitmask 0x80400042 for DisplayLevel if it matters and DisableWatchDog=No.

[config.plist.zip](https://github.com/acidanthera/bugtracker/files/3294038/config.plist.zip)
[opencore.log.zip](https://github.com/acidanthera/bugtracker/files/3294035/opencore.log.zip)

**Comment by vit9696** [comment]
`DisableWatchDog` must be set to `YES` to ensure there are no issues with the debug log. I have already mentioned it on applelife. Please redo the log with the current build, while we try to add more information.

**Comment by DHARVED** [comment]
Log with DisableWatchDog=YES.
[opencore.log.zip](https://github.com/acidanthera/bugtracker/files/3304985/opencore.log.zip)

**Comment by Download-Fritz** [comment]
@DHARVED Sorry for the lack of results. I attached a DEBUG OpenCore build based on master with plenty of debug messages added, which hopefully will point us in the right direction. Thanks for your patience!
[OpenCore.zip](https://github.com/acidanthera/bugtracker/files/3306639/OpenCore.zip)

**Comment by DHARVED** [comment]
My computer is temporarily broken. I won't be able to make a new log for a few weeks. Excuse me.

**Comment by Download-Fritz** [comment]
@DHARVED No problem, I hope you get that problem sorted as soon as you require.
I actually wondered whether the stall was a sign of a hardware defect, as literally nobody else reported such issues. We had a roughly similiar issue before when someone's storage was dieing.

Good luck!

**Comment by DHARVED** [comment]
I fixed my computer, it is a miracle.
With your OpenCore, I got a "Halting on critical error".
My storage is fine. I tested Recovery on SSD and NVME, and the result is one.

Maybe I'm doing something wrong? 
Sorry for disturbing your.

[opencore.log.zip](https://github.com/acidanthera/bugtracker/files/3312025/opencore.log.zip)

**Comment by vit9696** [comment]
This looks quite strange, as the log shows pretty much undetected recovery, when previously it was just failing somewhere. Was the bug relevant to the harddrive? I would like to run several tests in a row, perhaps we could arrange for some time via PM on applelife?

**Comment by vit9696** [comment]
Ok, after several tests it is clear that the issue happens during dmg file reading, which results in a stall when > 4 GB memory addresses are used in extent table.

Extensive physical RAM testing showed no issues of any kind with the modules, and each tested 4 GB module works in single mode in any slot. BIOS firmware is latest patched with newest microcode, NVMe driver, and ME firmware. Board name is GA Z77P-D3.

Since it clearly is firmware bug and there is little to no way to reliably detect it, I propose implementing UEFI quirk `AvoidHighAlloc`, which will set a dedicated NVRAM variable marking this problem, which can then be checked in many places including extent table allocation. The need for a quirk is justified by the fact that on some firmwares there may not be enough memory in lower addresses for both kernel and recovery dmg.

**Comment by vit9696** [comment]
@DHARVED should be implemented in master, please check =)

Quirk is named `AvoidHighAlloc` and is put to UEFI section. Enabling it on your board should hopefully fix recovery booting.

**Comment by cattyhouse** [comment]
@vit9696 is this issue related to [issue 399](https://github.com/acidanthera/bugtracker/issues/399)
