### ISSUE TITLE
Microcode revision read is broken in OcCpulib.c

### ISSUE THREAD

**Issue by startergo** [acidanthera/bugtracker#621]
Microcode revision read returns 0 with Westmere CPU. According to Intel SDM
"Assembly Code to Retrieve the Update Revision
MOV   ECX, 08BH                 
XOR   EAX, EAX                      
XOR   EDX, EDX                      
WRMSR                                   
MOV   EAX, 1
cpuid
MOV   ECX, 08BH                   
rdmsr                                        

Please see implementation in [Coreboot](https://chromium.googlesource.com/chromiumos/third_party/coreboot/+/broadwell_fsp/src/cpu/intel/microcode/microcode.c)
Lines 59 to 82

**Comment by startergo** [comment]
CHIPSEC also reads the microcode when booted from OC:
sudo ./chipsec_util.py msr 0x8b                                                             
Password:

################################################################
##                                                            ##
##  CHIPSEC: Platform Hardware Security Assessment Framework  ##
##                                                            ##
################################################################
[CHIPSEC] Version : 1.4.5
[CHIPSEC] OS      : Darwin 19.2.0 Darwin Kernel Version 19.2.0: Sat Nov  9 03:47:04 PST 2019; root:xnu-6153.61.1~20/RELEASE_X86_64 x86_64
[CHIPSEC] Python  : 2.7.16 (64-bit)
[CHIPSEC] API mode: using CHIPSEC kernel module API
ERROR: Unsupported Platform: VID = 0x8086, DID = 0x3406, RID = 0x22
WARNING: *******************************************************************
WARNING: * Unknown platform!
WARNING: * Platform dependent functionality will likely be incorrect
WARNING: * Error Message: "Unsupported Platform: VID = 0x8086, DID = 0x3406, RID = 0x22"
WARNING: *******************************************************************
[CHIPSEC] Helper  : OSXHelper (/Users/g5/Downloads/chipsec-1.4-2.5/chipsec/helper/osx/chipsec.kext)
[CHIPSEC] Platform: UnknownPlatform
[CHIPSEC]      VID: 8086
[CHIPSEC]      DID: 3406
[CHIPSEC]      RID: 22
[CHIPSEC] PCH     : Default PCH
[CHIPSEC]      VID: 8086
[CHIPSEC]      DID: 3A18
[CHIPSEC]      RID: 00
[CHIPSEC] Executing command 'msr' with args ['0x8b']

[CHIPSEC] CPU0: RDMSR( 0x8b ) = 0000001F00000000 (EAX=00000000, EDX=0000001F)
[CHIPSEC] CPU1: RDMSR( 0x8b ) = 0000001F00000000 (EAX=00000000, EDX=0000001F)
[CHIPSEC] CPU2: RDMSR( 0x8b ) = 0000001F00000000 (EAX=00000000, EDX=0000001F)
[CHIPSEC] CPU3: RDMSR( 0x8b ) = 0000001F00000000 (EAX=00000000, EDX=0000001F)
[CHIPSEC] CPU4: RDMSR( 0x8b ) = 0000001F00000000 (EAX=00000000, EDX=0000001F)
[CHIPSEC] CPU5: RDMSR( 0x8b ) = 0000001F00000000 (EAX=00000000, EDX=0000001F)
[CHIPSEC] CPU6: RDMSR( 0x8b ) = 0000001F00000000 (EAX=00000000, EDX=0000001F)
[CHIPSEC] CPU7: RDMSR( 0x8b ) = 0000001F00000000 (EAX=00000000, EDX=0000001F)
[CHIPSEC] CPU8: RDMSR( 0x8b ) = 0000001F00000000 (EAX=00000000, EDX=0000001F)
[CHIPSEC] CPU9: RDMSR( 0x8b ) = 0000001F00000000 (EAX=00000000, EDX=0000001F)
[CHIPSEC] CPU10: RDMSR( 0x8b ) = 0000001F00000000 (EAX=00000000, EDX=0000001F)
[CHIPSEC] CPU11: RDMSR( 0x8b ) = 0000001F00000000 (EAX=00000000, EDX=0000001F)
[CHIPSEC] CPU12: RDMSR( 0x8b ) = 0000001F00000000 (EAX=00000000, EDX=0000001F)
[CHIPSEC] CPU13: RDMSR( 0x8b ) = 0000001F00000000 (EAX=00000000, EDX=0000001F)
[CHIPSEC] CPU14: RDMSR( 0x8b ) = 0000001F00000000 (EAX=00000000, EDX=0000001F)
[CHIPSEC] CPU15: RDMSR( 0x8b ) = 0000001F00000000 (EAX=00000000, EDX=0000001F)
[CHIPSEC] CPU16: RDMSR( 0x8b ) = 0000001F00000000 (EAX=00000000, EDX=0000001F)
[CHIPSEC] CPU17: RDMSR( 0x8b ) = 0000001F00000000 (EAX=00000000, EDX=0000001F)
[CHIPSEC] CPU18: RDMSR( 0x8b ) = 0000001F00000000 (EAX=00000000, EDX=0000001F)
[CHIPSEC] CPU19: RDMSR( 0x8b ) = 0000001F00000000 (EAX=00000000, EDX=0000001F)
[CHIPSEC] CPU20: RDMSR( 0x8b ) = 0000001F00000000 (EAX=00000000, EDX=0000001F)
[CHIPSEC] CPU21: RDMSR( 0x8b ) = 0000001F00000000 (EAX=00000000, EDX=0000001F)
[CHIPSEC] CPU22: RDMSR( 0x8b ) = 0000001F00000000 (EAX=00000000, EDX=0000001F)
[CHIPSEC] CPU23: RDMSR( 0x8b ) = 0000001F00000000 (EAX=00000000, EDX=0000001F)

**Comment by vit9696** [comment]
Thanks for the report. Should be fixed in master, please report whether there are any issues.

**Comment by startergo** [comment]
Just recompiled the branch and tested it but still does not work:
sysctl -a | grep cpu                              
hw.ncpu: 24
hw.activecpu: 24
hw.physicalcpu: 12
hw.physicalcpu_max: 12
hw.logicalcpu: 24
hw.logicalcpu_max: 24
hw.cputype: 7
hw.cpusubtype: 4
hw.cpu64bit_capable: 1
hw.cpufamily: 1463508716
hw.cpufrequency: 3500000000
hw.cpufrequency_min: 3500000000
hw.cpufrequency_max: 3500000000
hw.cputhreadtype: 1
machdep.cpu.max_basic: 11
machdep.cpu.max_ext: 2147483656
machdep.cpu.vendor: GenuineIntel
machdep.cpu.brand_string: Intel(R) Xeon(R) CPU           X5690  @ 3.47GHz
machdep.cpu.family: 6
machdep.cpu.model: 44
machdep.cpu.extmodel: 2
machdep.cpu.extfamily: 0
machdep.cpu.stepping: 2
machdep.cpu.feature_bits: 188838921972218879
machdep.cpu.extfeature_bits: 5034215680
machdep.cpu.signature: 132802
machdep.cpu.brand: 0
machdep.cpu.features: FPU VME DE PSE TSC MSR PAE MCE CX8 APIC SEP MTRR PGE MCA CMOV PAT PSE36 CLFSH DS ACPI MMX FXSR SSE SSE2 SS HTT TM PBE SSE3 PCLMULQDQ DTES64 MON DSCPL VMX SMX EST TM2 SSSE3 CX16 TPR PDCM SSE4.1 SSE4.2 POPCNT AES PCID
machdep.cpu.extfeatures: SYSCALL XD 1GBPAGE EM64T LAHF RDTSCP TSCI
machdep.cpu.logical_per_package: 32
machdep.cpu.cores_per_package: 16
machdep.cpu.microcode_version: 0
machdep.cpu.processor_flag: 0
machdep.cpu.mwait.linesize_min: 64
machdep.cpu.mwait.linesize_max: 64
machdep.cpu.mwait.extensions: 3
machdep.cpu.mwait.sub_Cstates: 4384
machdep.cpu.thermal.sensor: 1
machdep.cpu.thermal.dynamic_acceleration: 1
machdep.cpu.thermal.invariant_APIC_timer: 1
machdep.cpu.thermal.thresholds: 2
machdep.cpu.thermal.ACNT_MCNT: 1
machdep.cpu.thermal.core_power_limits: 0
machdep.cpu.thermal.fine_grain_clock_mod: 0
machdep.cpu.thermal.package_thermal_intr: 0
machdep.cpu.thermal.hardware_feedback: 0
machdep.cpu.thermal.energy_policy: 0
machdep.cpu.arch_perf.version: 3
machdep.cpu.arch_perf.number: 4
machdep.cpu.arch_perf.width: 48
machdep.cpu.arch_perf.events_number: 7
machdep.cpu.arch_perf.events: 4
machdep.cpu.arch_perf.fixed_number: 3
machdep.cpu.arch_perf.fixed_width: 48
machdep.cpu.cache.linesize: 64
machdep.cpu.cache.L2_associativity: 8
machdep.cpu.cache.size: 256
machdep.cpu.tlb.inst.small: 64
machdep.cpu.tlb.inst.large: 7
machdep.cpu.tlb.data.small: 64
machdep.cpu.tlb.data.large: 32
machdep.cpu.tlb.shared: 512
machdep.cpu.address_bits.physical: 40
machdep.cpu.address_bits.virtual: 48
machdep.cpu.core_count: 6
machdep.cpu.thread_count: 12
machdep.cpu.tsc_ccc.numerator: 0
machdep.cpu.tsc_ccc.denominator: 0
machdep.xcpm.cpu_thermal_level: 0

**Comment by vit9696** [comment]
I have just added microcode revision printing to OpenCore logfile. Please recheck whether correct value if printed in `OCCPU: Signature %0X Stepping %0X Model %0X Family %0X Type %0X ExtModel %0X ExtFamily %0X uCode %0X` line.

Please note, that we are not responsible for macOS properly displaying uCode revision as long as CPUID patches are not enabled.

**Comment by startergo** [comment]
00:297 00:136 OCCPU: Signature 206C2 Stepping 2 Model 2C Family 6 Type 0 ExtModel 2 ExtFamily 0 uCode 0

**Comment by vit9696** [comment]
Sorry, fixed in master.

**Comment by startergo** [comment]
It works now. Thanks Vitalii!

sysctl -a | grep cpu                                        
hw.ncpu: 24
hw.activecpu: 24
hw.physicalcpu: 12
hw.physicalcpu_max: 12
hw.logicalcpu: 24
hw.logicalcpu_max: 24
hw.cputype: 7
hw.cpusubtype: 4
hw.cpu64bit_capable: 1
hw.cpufamily: 1463508716
hw.cpufrequency: 3500000000
hw.cpufrequency_min: 3500000000
hw.cpufrequency_max: 3500000000
hw.cputhreadtype: 1
machdep.cpu.max_basic: 11
machdep.cpu.max_ext: 2147483656
machdep.cpu.vendor: GenuineIntel
machdep.cpu.brand_string: Intel(R) Xeon(R) CPU           X5690  @ 3.47GHz
machdep.cpu.family: 6
machdep.cpu.model: 44
machdep.cpu.extmodel: 2
machdep.cpu.extfamily: 0
machdep.cpu.stepping: 2
machdep.cpu.feature_bits: 188838921972218879
machdep.cpu.extfeature_bits: 5034215680
machdep.cpu.signature: 132802
machdep.cpu.brand: 0
machdep.cpu.features: FPU VME DE PSE TSC MSR PAE MCE CX8 APIC SEP MTRR PGE MCA CMOV PAT PSE36 CLFSH DS ACPI MMX FXSR SSE SSE2 SS HTT TM PBE SSE3 PCLMULQDQ DTES64 MON DSCPL VMX SMX EST TM2 SSSE3 CX16 TPR PDCM SSE4.1 SSE4.2 POPCNT AES PCID
machdep.cpu.extfeatures: SYSCALL XD 1GBPAGE EM64T LAHF RDTSCP TSCI
machdep.cpu.logical_per_package: 32
machdep.cpu.cores_per_package: 16
machdep.cpu.microcode_version: 31
machdep.cpu.processor_flag: 0
machdep.cpu.mwait.linesize_min: 64
machdep.cpu.mwait.linesize_max: 64
machdep.cpu.mwait.extensions: 3
machdep.cpu.mwait.sub_Cstates: 4384
machdep.cpu.thermal.sensor: 1
machdep.cpu.thermal.dynamic_acceleration: 1
machdep.cpu.thermal.invariant_APIC_timer: 1
machdep.cpu.thermal.thresholds: 2
machdep.cpu.thermal.ACNT_MCNT: 1
machdep.cpu.thermal.core_power_limits: 0
machdep.cpu.thermal.fine_grain_clock_mod: 0
machdep.cpu.thermal.package_thermal_intr: 0
machdep.cpu.thermal.hardware_feedback: 0
machdep.cpu.thermal.energy_policy: 0
machdep.cpu.arch_perf.version: 3
machdep.cpu.arch_perf.number: 4
machdep.cpu.arch_perf.width: 48
machdep.cpu.arch_perf.events_number: 7
machdep.cpu.arch_perf.events: 4
machdep.cpu.arch_perf.fixed_number: 3
machdep.cpu.arch_perf.fixed_width: 48
machdep.cpu.cache.linesize: 64
machdep.cpu.cache.L2_associativity: 8
machdep.cpu.cache.size: 256
machdep.cpu.tlb.inst.small: 64
machdep.cpu.tlb.inst.large: 7
machdep.cpu.tlb.data.small: 64
machdep.cpu.tlb.data.large: 32
machdep.cpu.tlb.shared: 512
machdep.cpu.address_bits.physical: 40
machdep.cpu.address_bits.virtual: 48
machdep.cpu.core_count: 6
machdep.cpu.thread_count: 12
machdep.cpu.tsc_ccc.numerator: 0
machdep.cpu.tsc_ccc.denominator: 0
machdep.xcpm.cpu_thermal_level: 0

00:300 00:072 OCCPU: Signature 206C2 Stepping 2 Model 2C Family 6 Type 0 ExtModel 2 ExtFamily 0 uCode 1F
